name: Run Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Verify project structure
      run: |
        echo "Project structure:"
        ls -la
        echo "TypeScript config:"
        cat tsconfig.json | head -20

    - name: Run tests
      run: npm run test

    - name: Run build
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Checking for tsconfig.json:"
        ls -la tsconfig.json || echo "tsconfig.json not found"
        echo "Running TypeScript compiler directly:"
        npx tsc --version
        npx tsc -p ./tsconfig.json

    - name: Upload coverage reports
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: false
